version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
cache: C:\Users\appveyor\.dnx
build_script:
- cmd: >-
    cd ./src/WindowsUtils.Core
    
    dotnet restore
    
    dotnet pack -c release
    
    cd ../..

test_script:
- cmd: >-
    cd ./src/WindowsUtils.Core.Tests

    dotnet restore

    dotnet test

    cd ../..

artifacts:
- path: ./src/WindowsUtils.Core/bin/release/*.nupkg
  name: NuGet 

deploy:
- provider: NuGet
  api_key:
    secure: sY6XD31OwuiRfReoU86FgHqk9VB218ncK79FyHLChge05nUdmlAscOIDJARy7r22
  skip_symbols: true

notifications:
- provider: Email
  to:
  - arasoulian@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true 
